with expected(id, name, category) as (
  values
  ('programador-web', 'Programador Web', 'Tecnologia'),
  ('desarrollador-backend', 'Desarrollador Backend', 'Tecnologia'),
  ('desarrollador-frontend', 'Desarrollador Frontend', 'Tecnologia'),
  ('desarrollador-fullstack', 'Desarrollador Full Stack', 'Tecnologia'),
  ('desarrollador-mobile', 'Desarrollador Mobile', 'Tecnologia'),
  ('qa-tester', 'QA Tester', 'Tecnologia'),
  ('qa-automation', 'QA Automation', 'Tecnologia'),
  ('devops-sre', 'DevOps / SRE', 'Tecnologia'),
  ('data-scientist', 'Data Scientist', 'Tecnologia'),
  ('data-engineer', 'Data Engineer', 'Tecnologia'),
  ('analista-de-datos', 'Analista de Datos', 'Tecnologia'),
  ('analista-bi', 'Analista BI', 'Tecnologia'),
  ('product-manager', 'Product Manager', 'Tecnologia'),
  ('project-manager-it', 'Project Manager IT', 'Tecnologia'),
  ('scrum-master', 'Scrum Master', 'Tecnologia'),
  ('disenador-ux-ui', 'Disenador UX/UI', 'Tecnologia'),
  ('product-designer', 'Product Designer', 'Tecnologia'),
  ('soporte-tecnico', 'Soporte Tecnico', 'Tecnologia'),
  ('help-desk', 'Help Desk', 'Tecnologia'),
  ('administrador-redes', 'Administrador de Redes', 'Tecnologia'),
  ('sysadmin', 'Administrador de Sistemas', 'Tecnologia'),
  ('ciberseguridad', 'Especialista en Ciberseguridad', 'Tecnologia'),
  ('implementador-erp-crm', 'Implementador ERP / CRM', 'Tecnologia'),
  ('consultor-sap', 'Consultor SAP', 'Tecnologia'),
  ('medico-clinico', 'Medico Clinico', 'Salud'),
  ('medico-pediatra', 'Medico Pediatra', 'Salud'),
  ('medico-cardiologo', 'Medico Cardiologo', 'Salud'),
  ('medico-psiquiatra', 'Medico Psiquiatra', 'Salud'),
  ('medico-ginecologo', 'Medico Ginecologo', 'Salud'),
  ('medico-traumatologo', 'Medico Traumatologo', 'Salud'),
  ('medico-dermatologo', 'Medico Dermatologo', 'Salud'),
  ('medico-anestesista', 'Medico Anestesista', 'Salud'),
  ('enfermero', 'Enfermero/a', 'Salud'),
  ('auxiliar-enfermeria', 'Auxiliar de Enfermeria', 'Salud'),
  ('odontologo', 'Odontologo/a', 'Salud'),
  ('psicologo', 'Psicologo/a', 'Salud'),
  ('kinesiologo', 'Kinesiologo/a', 'Salud'),
  ('nutricionista', 'Nutricionista', 'Salud'),
  ('farmaceutico', 'Farmaceutico/a', 'Salud'),
  ('bioquimico', 'Bioquimico/a', 'Salud'),
  ('fonoaudiologo', 'Fonoaudiologo/a', 'Salud'),
  ('acompanante-terapeutico', 'Acompanante Terapeutico', 'Salud'),
  ('cuidador-domiciliario', 'Cuidador/a Domiciliario', 'Salud'),
  ('tecnico-radiologo', 'Tecnico/a Radiologo', 'Salud'),
  ('instrumentador-quirurgico', 'Instrumentador/a Quirurgico', 'Salud'),
  ('camillero', 'Camillero/a', 'Salud'),
  ('administrativo-salud', 'Administrativo/a de Salud', 'Salud'),
  ('docente-inicial', 'Docente Nivel Inicial', 'Educacion'),
  ('docente-primaria', 'Docente Nivel Primario', 'Educacion'),
  ('docente-secundaria', 'Docente Nivel Secundario', 'Educacion'),
  ('docente-universitario', 'Docente Universitario', 'Educacion'),
  ('profesor-ingles', 'Profesor/a de Ingles', 'Educacion'),
  ('profesor-educacion-fisica', 'Profesor/a de Educacion Fisica', 'Educacion'),
  ('preceptor', 'Preceptor/a', 'Educacion'),
  ('director-escuela', 'Director/a de Escuela', 'Educacion'),
  ('psicopedagogo', 'Psicopedagogo/a', 'Educacion'),
  ('tutor-online', 'Tutor/a Online', 'Educacion'),
  ('profesor-particular', 'Profesor/a Particular', 'Educacion'),
  ('plomero', 'Plomero', 'Oficios y Construccion'),
  ('electricista', 'Electricista', 'Oficios y Construccion'),
  ('gasista', 'Gasista Matriculado', 'Oficios y Construccion'),
  ('albanil', 'Albanil', 'Oficios y Construccion'),
  ('carpintero', 'Carpintero/a', 'Oficios y Construccion'),
  ('herrero', 'Herrero/a', 'Oficios y Construccion'),
  ('pintor', 'Pintor/a', 'Oficios y Construccion'),
  ('mecanico-automotor', 'Mecanico/a Automotor', 'Oficios y Construccion'),
  ('cerrajero', 'Cerrajero/a', 'Oficios y Construccion'),
  ('tecnico-aire-acondicionado', 'Tecnico/a Aire Acondicionado', 'Oficios y Construccion'),
  ('tecnico-refrigeracion', 'Tecnico/a Refrigeracion', 'Oficios y Construccion'),
  ('jardinero', 'Jardinero/a', 'Oficios y Construccion'),
  ('piletero', 'Piletero/a', 'Oficios y Construccion'),
  ('fumigador', 'Fumigador/a', 'Oficios y Construccion'),
  ('techista', 'Techista', 'Oficios y Construccion'),
  ('durlockero', 'Durlockero/a', 'Oficios y Construccion'),
  ('soldador', 'Soldador/a', 'Oficios y Construccion'),
  ('maestro-mayor-obras', 'Maestro Mayor de Obras', 'Oficios y Construccion'),
  ('vendedor-local', 'Vendedor/a de Local', 'Comercio y Ventas'),
  ('cajero', 'Cajero/a', 'Comercio y Ventas'),
  ('repositor', 'Repositor/a', 'Comercio y Ventas'),
  ('encargado-local', 'Encargado/a de Local', 'Comercio y Ventas'),
  ('supervisor-local', 'Supervisor/a de Local', 'Comercio y Ventas'),
  ('preventista', 'Preventista', 'Comercio y Ventas'),
  ('vendedor-telefonico', 'Vendedor/a Telefonico', 'Comercio y Ventas'),
  ('telemarketer', 'Telemarketer', 'Comercio y Ventas'),
  ('atencion-cliente', 'Atencion al Cliente', 'Comercio y Ventas'),
  ('customer-support', 'Customer Support', 'Comercio y Ventas'),
  ('customer-success', 'Customer Success', 'Comercio y Ventas'),
  ('promotor', 'Promotor/a', 'Comercio y Ventas'),
  ('merchandiser', 'Merchandiser', 'Comercio y Ventas'),
  ('corredor-inmobiliario', 'Corredor/a Inmobiliario/a', 'Comercio y Ventas'),
  ('cocinero', 'Cocinero/a', 'Gastronomia'),
  ('chef', 'Chef', 'Gastronomia'),
  ('mozo-camarero', 'Mozo/a / Camarero/a', 'Gastronomia'),
  ('barista', 'Barista', 'Gastronomia'),
  ('bartender', 'Bartender', 'Gastronomia'),
  ('ayudante-cocina', 'Ayudante de Cocina', 'Gastronomia'),
  ('bachero', 'Bachero/a', 'Gastronomia'),
  ('pastelero', 'Pastelero/a', 'Gastronomia'),
  ('panadero', 'Panadero/a', 'Gastronomia'),
  ('parrillero', 'Parrillero/a', 'Gastronomia'),
  ('pizzero', 'Pizzero/a', 'Gastronomia'),
  ('jefe-cocina', 'Jefe/a de Cocina', 'Gastronomia'),
  ('encargado-restaurante', 'Encargado/a de Restaurante', 'Gastronomia'),
  ('recepcionista-hotel', 'Recepcionista de Hotel', 'Gastronomia'),
  ('mucama-hotel', 'Mucama/o de Hotel', 'Gastronomia'),
  ('contador-publico', 'Contador/a Publico/a', 'Administracion y Finanzas'),
  ('administrativo', 'Administrativo/a', 'Administracion y Finanzas'),
  ('asistente-administrativo', 'Asistente Administrativo', 'Administracion y Finanzas'),
  ('data-entry', 'Data Entry / Carga de Datos', 'Administracion y Finanzas'),
  ('recepcionista', 'Recepcionista', 'Administracion y Finanzas'),
  ('secretario', 'Secretario/a', 'Administracion y Finanzas'),
  ('analista-contable', 'Analista Contable', 'Administracion y Finanzas'),
  ('analista-financiero', 'Analista Financiero', 'Administracion y Finanzas'),
  ('liquidador-sueldos', 'Liquidador/a de Sueldos', 'Administracion y Finanzas'),
  ('auditor', 'Auditor/a', 'Administracion y Finanzas'),
  ('tesorero', 'Tesorero/a', 'Administracion y Finanzas'),
  ('analista-facturacion', 'Analista de Facturacion', 'Administracion y Finanzas'),
  ('analista-compras', 'Analista de Compras', 'Administracion y Finanzas'),
  ('analista-rrhh', 'Analista de RRHH', 'Administracion y Finanzas'),
  ('recruiter', 'Recruiter / Selector/a de Personal', 'Administracion y Finanzas'),
  ('payroll', 'Payroll', 'Administracion y Finanzas'),
  ('ejecutivo-cuentas', 'Ejecutivo/a de Cuentas', 'Administracion y Finanzas'),
  ('asistente-virtual', 'Asistente Virtual', 'Administracion y Finanzas'),
  ('cadete-administrativo', 'Cadete Administrativo', 'Administracion y Finanzas'),
  ('ingeniero-civil', 'Ingeniero/a Civil', 'Ingenieria'),
  ('ingeniero-industrial', 'Ingeniero/a Industrial', 'Ingenieria'),
  ('ingeniero-mecanico', 'Ingeniero/a Mecanico/a', 'Ingenieria'),
  ('ingeniero-electronico', 'Ingeniero/a Electronico/a', 'Ingenieria'),
  ('ingeniero-quimico', 'Ingeniero/a Quimico/a', 'Ingenieria'),
  ('ingeniero-sistemas', 'Ingeniero/a en Sistemas', 'Ingenieria'),
  ('arquitecto', 'Arquitecto/a', 'Ingenieria y Construccion'),
  ('agrimensor', 'Agrimensor/a', 'Ingenieria y Construccion'),
  ('abogado', 'Abogado/a General', 'Legales'),
  ('abogado-laboralista', 'Abogado/a Laboralista', 'Legales'),
  ('abogado-penalista', 'Abogado/a Penalista', 'Legales'),
  ('abogado-civil', 'Abogado/a Civil', 'Legales'),
  ('abogado-corporativo', 'Abogado/a Corporativo', 'Legales'),
  ('escribano', 'Escribano/a', 'Legales'),
  ('paralegal', 'Paralegal / Asistente Legal', 'Legales'),
  ('procurador', 'Procurador/a', 'Legales'),
  ('disenador-grafico', 'Disenador/a Grafico/a', 'Diseno y Comunicacion'),
  ('community-manager', 'Community Manager', 'Diseno y Comunicacion'),
  ('redactor-copywriter', 'Redactor/a / Copywriter', 'Diseno y Comunicacion'),
  ('periodista', 'Periodista', 'Diseno y Comunicacion'),
  ('editor-video', 'Editor/a de Video', 'Diseno y Comunicacion'),
  ('fotografo', 'Fotografo/a', 'Diseno y Comunicacion'),
  ('productor-audiovisual', 'Productor/a Audiovisual', 'Diseno y Comunicacion'),
  ('especialista-seo', 'Especialista SEO', 'Diseno y Comunicacion'),
  ('paid-media', 'Especialista SEM / Paid Media', 'Diseno y Comunicacion'),
  ('analista-marketing', 'Analista de Marketing', 'Diseno y Comunicacion'),
  ('social-media-manager', 'Social Media Manager', 'Diseno y Comunicacion'),
  ('disenador-industrial', 'Disenador/a Industrial', 'Diseno y Comunicacion'),
  ('disenador-indumentaria', 'Disenador/a de Indumentaria', 'Diseno y Comunicacion'),
  ('chofer-camion', 'Chofer de Camion', 'Logistica y Transporte'),
  ('chofer-colectivo', 'Chofer de Colectivo', 'Logistica y Transporte'),
  ('taxista-remisero', 'Taxista / Remisero / Uber / Cabify', 'Logistica y Transporte'),
  ('repartidor', 'Repartidor/a', 'Logistica y Transporte'),
  ('chofer-reparto', 'Chofer de Reparto', 'Logistica y Transporte'),
  ('operario-deposito', 'Operario/a de Deposito', 'Logistica y Transporte'),
  ('clarkista', 'Clarkista / Autoelevadorista', 'Logistica y Transporte'),
  ('preparador-pedidos', 'Preparador/a de Pedidos', 'Logistica y Transporte'),
  ('supervisor-logistica', 'Supervisor/a de Logistica', 'Logistica y Transporte'),
  ('analista-logistica', 'Analista de Logistica', 'Logistica y Transporte'),
  ('despachante-aduana', 'Despachante de Aduana', 'Logistica y Transporte'),
  ('administrativo-trafico', 'Administrativo/a de Trafico', 'Logistica y Transporte'),
  ('operario-produccion', 'Operario/a de Produccion', 'Industria y Produccion'),
  ('operario-metalurgico', 'Operario/a Metalurgico', 'Industria y Produccion'),
  ('operario-textil', 'Operario/a Textil', 'Industria y Produccion'),
  ('operario-alimenticio', 'Operario/a Alimenticio', 'Industria y Produccion'),
  ('tecnico-electromecanico', 'Tecnico/a Electromecanico', 'Industria y Produccion'),
  ('tecnico-mecanico', 'Tecnico/a Mecanico', 'Industria y Produccion'),
  ('electricista-industrial', 'Electricista Industrial', 'Industria y Produccion'),
  ('supervisor-produccion', 'Supervisor/a de Produccion', 'Industria y Produccion'),
  ('jefe-planta', 'Jefe/a de Planta', 'Industria y Produccion'),
  ('control-calidad', 'Control de Calidad', 'Industria y Produccion'),
  ('inspector-calidad', 'Inspector/a de Calidad', 'Industria y Produccion'),
  ('mantenimiento-industrial', 'Mantenimiento Industrial', 'Industria y Produccion'),
  ('tornero', 'Tornero/a', 'Industria y Produccion'),
  ('matricero', 'Matricero/a', 'Industria y Produccion'),
  ('peon-rural', 'Peon Rural', 'Agro y Rural'),
  ('tractorista', 'Tractorista', 'Agro y Rural'),
  ('ingeniero-agronomo', 'Ingeniero/a Agronomo', 'Agro y Rural'),
  ('veterinario', 'Veterinario/a', 'Agro y Rural'),
  ('tambero', 'Tambero/a', 'Agro y Rural'),
  ('encargado-campo', 'Encargado/a de Campo', 'Agro y Rural'),
  ('operario-avicola', 'Operario/a Avicola', 'Agro y Rural'),
  ('operario-frigorifico', 'Operario/a Frigorifico', 'Agro y Rural'),
  ('tecnico-agropecuario', 'Tecnico/a Agropecuario', 'Agro y Rural'),
  ('policia', 'Policia', 'Seguridad'),
  ('vigilador-privado', 'Vigilador/a Privado/a', 'Seguridad'),
  ('bombero', 'Bombero/a', 'Seguridad'),
  ('militar', 'Militar', 'Seguridad'),
  ('gendarme-prefecto', 'Gendarme / Prefecto', 'Seguridad'),
  ('operador-monitoreo', 'Operador/a de Monitoreo', 'Seguridad'),
  ('custodio', 'Custodio/a', 'Seguridad'),
  ('empleada-domestica', 'Personal de Casas Particulares', 'Servicios Personales'),
  ('peluquero', 'Peluquero/a', 'Servicios Personales'),
  ('barbero', 'Barbero/a', 'Servicios Personales'),
  ('esteticista', 'Esteticista', 'Servicios Personales'),
  ('cosmetologo', 'Cosmetologo/a', 'Servicios Personales'),
  ('manicura', 'Manicura', 'Servicios Personales'),
  ('masajista', 'Masajista', 'Servicios Personales'),
  ('entrenador-personal', 'Entrenador/a Personal', 'Servicios Personales'),
  ('profesor-yoga-pilates', 'Profesor/a de Yoga / Pilates', 'Servicios Personales'),
  ('paseador-perros', 'Paseador/a de Perros', 'Servicios Personales'),
  ('ninera', 'Ninera', 'Servicios Personales'),
  ('creador-contenido', 'Creador/a de Contenido', 'Otros'),
  ('streamer', 'Streamer', 'Otros'),
  ('musico', 'Musico/a', 'Otros'),
  ('artista', 'Artista', 'Otros'),
  ('traductor', 'Traductor/a', 'Otros'),
  ('guia-turismo', 'Guia de Turismo', 'Otros')
)
select expected.id, expected.name, expected.category
from expected
left join public.professions on professions.id = expected.id
where professions.id is null
order by expected.category, expected.name;
