insert into public.professions (id, slug, name, category, keywords) values
  ('programador-web', 'programador-web', 'Programador Web', 'Tecnologia', array['desarrollador', 'developer', 'sistemas', 'programacion']),
  ('desarrollador-backend', 'desarrollador-backend', 'Desarrollador Backend', 'Tecnologia', array['programador', 'developer', 'api', 'back']),
  ('desarrollador-frontend', 'desarrollador-frontend', 'Desarrollador Frontend', 'Tecnologia', array['programador', 'developer', 'react', 'front']),
  ('desarrollador-fullstack', 'desarrollador-fullstack', 'Desarrollador Full Stack', 'Tecnologia', array['fullstack', 'programador', 'developer']),
  ('desarrollador-mobile', 'desarrollador-mobile', 'Desarrollador Mobile', 'Tecnologia', array['android', 'ios', 'react native', 'flutter']),
  ('qa-tester', 'qa-tester', 'QA Tester', 'Tecnologia', array['testing', 'calidad', 'tester']),
  ('qa-automation', 'qa-automation', 'QA Automation', 'Tecnologia', array['testing', 'automation', 'selenium', 'cypress']),
  ('devops-sre', 'devops-sre', 'DevOps / SRE', 'Tecnologia', array['infraestructura', 'cloud', 'kubernetes', 'aws']),
  ('data-scientist', 'data-scientist', 'Data Scientist', 'Tecnologia', array['ciencia de datos', 'machine learning', 'ai']),
  ('data-engineer', 'data-engineer', 'Data Engineer', 'Tecnologia', array['ingeniero de datos', 'etl', 'big data']),
  ('analista-de-datos', 'analista-de-datos', 'Analista de Datos', 'Tecnologia', array['data', 'analytics', 'bi']),
  ('analista-bi', 'analista-bi', 'Analista BI', 'Tecnologia', array['business intelligence', 'power bi', 'tableau']),
  ('product-manager', 'product-manager', 'Product Manager', 'Tecnologia', array['pm', 'producto']),
  ('project-manager-it', 'project-manager-it', 'Project Manager IT', 'Tecnologia', array['proyectos', 'it', 'pmo']),
  ('scrum-master', 'scrum-master', 'Scrum Master', 'Tecnologia', array['agile', 'facilitador']),
  ('disenador-ux-ui', 'disenador-ux-ui', 'Disenador UX/UI', 'Tecnologia', array['design', 'web', 'interfaces']),
  ('product-designer', 'product-designer', 'Product Designer', 'Tecnologia', array['ux', 'ui', 'figma']),
  ('soporte-tecnico', 'soporte-tecnico', 'Soporte Tecnico', 'Tecnologia', array['sistemas', 'helpdesk', 'it']),
  ('help-desk', 'help-desk', 'Help Desk', 'Tecnologia', array['mesa de ayuda', 'soporte nivel 1']),
  ('administrador-redes', 'administrador-redes', 'Administrador de Redes', 'Tecnologia', array['networking', 'redes', 'it']),
  ('sysadmin', 'sysadmin', 'Administrador de Sistemas', 'Tecnologia', array['linux', 'windows server', 'infraestructura']),
  ('ciberseguridad', 'ciberseguridad', 'Especialista en Ciberseguridad', 'Tecnologia', array['seguridad informatica', 'security']),
  ('implementador-erp-crm', 'implementador-erp-crm', 'Implementador ERP / CRM', 'Tecnologia', array['sap', 'salesforce', 'odoo', 'hubspot']),
  ('consultor-sap', 'consultor-sap', 'Consultor SAP', 'Tecnologia', array['erp', 'abap', 'fi', 'mm']),
  ('medico-clinico', 'medico-clinico', 'Medico Clinico', 'Salud', array[]::text[]),
  ('medico-pediatra', 'medico-pediatra', 'Medico Pediatra', 'Salud', array[]::text[]),
  ('medico-cardiologo', 'medico-cardiologo', 'Medico Cardiologo', 'Salud', array[]::text[]),
  ('medico-psiquiatra', 'medico-psiquiatra', 'Medico Psiquiatra', 'Salud', array[]::text[]),
  ('medico-ginecologo', 'medico-ginecologo', 'Medico Ginecologo', 'Salud', array[]::text[]),
  ('medico-traumatologo', 'medico-traumatologo', 'Medico Traumatologo', 'Salud', array[]::text[]),
  ('medico-dermatologo', 'medico-dermatologo', 'Medico Dermatologo', 'Salud', array[]::text[]),
  ('medico-anestesista', 'medico-anestesista', 'Medico Anestesista', 'Salud', array[]::text[]),
  ('enfermero', 'enfermero', 'Enfermero/a', 'Salud', array[]::text[]),
  ('auxiliar-enfermeria', 'auxiliar-enfermeria', 'Auxiliar de Enfermeria', 'Salud', array[]::text[]),
  ('odontologo', 'odontologo', 'Odontologo/a', 'Salud', array[]::text[]),
  ('psicologo', 'psicologo', 'Psicologo/a', 'Salud', array[]::text[]),
  ('kinesiologo', 'kinesiologo', 'Kinesiologo/a', 'Salud', array[]::text[]),
  ('nutricionista', 'nutricionista', 'Nutricionista', 'Salud', array[]::text[]),
  ('farmaceutico', 'farmaceutico', 'Farmaceutico/a', 'Salud', array[]::text[]),
  ('bioquimico', 'bioquimico', 'Bioquimico/a', 'Salud', array[]::text[]),
  ('fonoaudiologo', 'fonoaudiologo', 'Fonoaudiologo/a', 'Salud', array[]::text[]),
  ('acompanante-terapeutico', 'acompanante-terapeutico', 'Acompanante Terapeutico', 'Salud', array[]::text[]),
  ('cuidador-domiciliario', 'cuidador-domiciliario', 'Cuidador/a Domiciliario', 'Salud', array[]::text[]),
  ('tecnico-radiologo', 'tecnico-radiologo', 'Tecnico/a Radiologo', 'Salud', array[]::text[]),
  ('instrumentador-quirurgico', 'instrumentador-quirurgico', 'Instrumentador/a Quirurgico', 'Salud', array[]::text[]),
  ('camillero', 'camillero', 'Camillero/a', 'Salud', array[]::text[]),
  ('administrativo-salud', 'administrativo-salud', 'Administrativo/a de Salud', 'Salud', array[]::text[]),
  ('docente-inicial', 'docente-inicial', 'Docente Nivel Inicial', 'Educacion', array[]::text[]),
  ('docente-primaria', 'docente-primaria', 'Docente Nivel Primario', 'Educacion', array[]::text[]),
  ('docente-secundaria', 'docente-secundaria', 'Docente Nivel Secundario', 'Educacion', array[]::text[]),
  ('docente-universitario', 'docente-universitario', 'Docente Universitario', 'Educacion', array[]::text[]),
  ('profesor-ingles', 'profesor-ingles', 'Profesor/a de Ingles', 'Educacion', array[]::text[]),
  ('profesor-educacion-fisica', 'profesor-educacion-fisica', 'Profesor/a de Educacion Fisica', 'Educacion', array[]::text[]),
  ('preceptor', 'preceptor', 'Preceptor/a', 'Educacion', array[]::text[]),
  ('director-escuela', 'director-escuela', 'Director/a de Escuela', 'Educacion', array[]::text[]),
  ('psicopedagogo', 'psicopedagogo', 'Psicopedagogo/a', 'Educacion', array[]::text[]),
  ('tutor-online', 'tutor-online', 'Tutor/a Online', 'Educacion', array[]::text[]),
  ('profesor-particular', 'profesor-particular', 'Profesor/a Particular', 'Educacion', array[]::text[]),
  ('plomero', 'plomero', 'Plomero', 'Oficios y Construccion', array[]::text[]),
  ('electricista', 'electricista', 'Electricista', 'Oficios y Construccion', array[]::text[]),
  ('gasista', 'gasista', 'Gasista Matriculado', 'Oficios y Construccion', array[]::text[]),
  ('albanil', 'albanil', 'Albanil', 'Oficios y Construccion', array[]::text[]),
  ('carpintero', 'carpintero', 'Carpintero/a', 'Oficios y Construccion', array[]::text[]),
  ('herrero', 'herrero', 'Herrero/a', 'Oficios y Construccion', array[]::text[]),
  ('pintor', 'pintor', 'Pintor/a', 'Oficios y Construccion', array[]::text[]),
  ('mecanico-automotor', 'mecanico-automotor', 'Mecanico/a Automotor', 'Oficios y Construccion', array[]::text[]),
  ('cerrajero', 'cerrajero', 'Cerrajero/a', 'Oficios y Construccion', array[]::text[]),
  ('tecnico-aire-acondicionado', 'tecnico-aire-acondicionado', 'Tecnico/a Aire Acondicionado', 'Oficios y Construccion', array[]::text[]),
  ('tecnico-refrigeracion', 'tecnico-refrigeracion', 'Tecnico/a Refrigeracion', 'Oficios y Construccion', array[]::text[]),
  ('jardinero', 'jardinero', 'Jardinero/a', 'Oficios y Construccion', array[]::text[]),
  ('piletero', 'piletero', 'Piletero/a', 'Oficios y Construccion', array[]::text[]),
  ('fumigador', 'fumigador', 'Fumigador/a', 'Oficios y Construccion', array[]::text[]),
  ('techista', 'techista', 'Techista', 'Oficios y Construccion', array[]::text[]),
  ('durlockero', 'durlockero', 'Durlockero/a', 'Oficios y Construccion', array[]::text[]),
  ('soldador', 'soldador', 'Soldador/a', 'Oficios y Construccion', array[]::text[]),
  ('maestro-mayor-obras', 'maestro-mayor-obras', 'Maestro Mayor de Obras', 'Oficios y Construccion', array[]::text[]),
  ('vendedor-local', 'vendedor-local', 'Vendedor/a de Local', 'Comercio y Ventas', array[]::text[]),
  ('cajero', 'cajero', 'Cajero/a', 'Comercio y Ventas', array[]::text[]),
  ('repositor', 'repositor', 'Repositor/a', 'Comercio y Ventas', array[]::text[]),
  ('encargado-local', 'encargado-local', 'Encargado/a de Local', 'Comercio y Ventas', array[]::text[]),
  ('supervisor-local', 'supervisor-local', 'Supervisor/a de Local', 'Comercio y Ventas', array[]::text[]),
  ('preventista', 'preventista', 'Preventista', 'Comercio y Ventas', array[]::text[]),
  ('vendedor-telefonico', 'vendedor-telefonico', 'Vendedor/a Telefonico', 'Comercio y Ventas', array[]::text[]),
  ('telemarketer', 'telemarketer', 'Telemarketer', 'Comercio y Ventas', array[]::text[]),
  ('atencion-cliente', 'atencion-cliente', 'Atencion al Cliente', 'Comercio y Ventas', array[]::text[]),
  ('customer-support', 'customer-support', 'Customer Support', 'Comercio y Ventas', array[]::text[]),
  ('customer-success', 'customer-success', 'Customer Success', 'Comercio y Ventas', array[]::text[]),
  ('promotor', 'promotor', 'Promotor/a', 'Comercio y Ventas', array[]::text[]),
  ('merchandiser', 'merchandiser', 'Merchandiser', 'Comercio y Ventas', array[]::text[]),
  ('corredor-inmobiliario', 'corredor-inmobiliario', 'Corredor/a Inmobiliario/a', 'Comercio y Ventas', array[]::text[]),
  ('cocinero', 'cocinero', 'Cocinero/a', 'Gastronomia', array[]::text[]),
  ('chef', 'chef', 'Chef', 'Gastronomia', array[]::text[]),
  ('mozo-camarero', 'mozo-camarero', 'Mozo/a / Camarero/a', 'Gastronomia', array['camarero', 'mozo', 'waiter']),
  ('barista', 'barista', 'Barista', 'Gastronomia', array[]::text[]),
  ('bartender', 'bartender', 'Bartender', 'Gastronomia', array[]::text[]),
  ('ayudante-cocina', 'ayudante-cocina', 'Ayudante de Cocina', 'Gastronomia', array[]::text[]),
  ('bachero', 'bachero', 'Bachero/a', 'Gastronomia', array[]::text[]),
  ('pastelero', 'pastelero', 'Pastelero/a', 'Gastronomia', array[]::text[]),
  ('panadero', 'panadero', 'Panadero/a', 'Gastronomia', array[]::text[]),
  ('parrillero', 'parrillero', 'Parrillero/a', 'Gastronomia', array[]::text[]),
  ('pizzero', 'pizzero', 'Pizzero/a', 'Gastronomia', array[]::text[]),
  ('jefe-cocina', 'jefe-cocina', 'Jefe/a de Cocina', 'Gastronomia', array[]::text[]),
  ('encargado-restaurante', 'encargado-restaurante', 'Encargado/a de Restaurante', 'Gastronomia', array[]::text[]),
  ('recepcionista-hotel', 'recepcionista-hotel', 'Recepcionista de Hotel', 'Gastronomia', array[]::text[]),
  ('mucama-hotel', 'mucama-hotel', 'Mucama/o de Hotel', 'Gastronomia', array[]::text[]),
  ('contador-publico', 'contador-publico', 'Contador/a Publico/a', 'Administracion y Finanzas', array[]::text[]),
  ('administrativo', 'administrativo', 'Administrativo/a', 'Administracion y Finanzas', array[]::text[]),
  ('asistente-administrativo', 'asistente-administrativo', 'Asistente Administrativo', 'Administracion y Finanzas', array[]::text[]),
  ('data-entry', 'data-entry', 'Data Entry / Carga de Datos', 'Administracion y Finanzas', array['data enter', 'data entry', 'carga de datos', 'administrativo']),
  ('recepcionista', 'recepcionista', 'Recepcionista', 'Administracion y Finanzas', array[]::text[]),
  ('secretario', 'secretario', 'Secretario/a', 'Administracion y Finanzas', array[]::text[]),
  ('analista-contable', 'analista-contable', 'Analista Contable', 'Administracion y Finanzas', array[]::text[]),
  ('analista-financiero', 'analista-financiero', 'Analista Financiero', 'Administracion y Finanzas', array[]::text[]),
  ('liquidador-sueldos', 'liquidador-sueldos', 'Liquidador/a de Sueldos', 'Administracion y Finanzas', array[]::text[]),
  ('auditor', 'auditor', 'Auditor/a', 'Administracion y Finanzas', array[]::text[]),
  ('tesorero', 'tesorero', 'Tesorero/a', 'Administracion y Finanzas', array[]::text[]),
  ('analista-facturacion', 'analista-facturacion', 'Analista de Facturacion', 'Administracion y Finanzas', array[]::text[]),
  ('analista-compras', 'analista-compras', 'Analista de Compras', 'Administracion y Finanzas', array[]::text[]),
  ('analista-rrhh', 'analista-rrhh', 'Analista de RRHH', 'Administracion y Finanzas', array['recursos humanos']),
  ('recruiter', 'recruiter', 'Recruiter / Selector/a de Personal', 'Administracion y Finanzas', array['seleccion', 'rrhh']),
  ('payroll', 'payroll', 'Payroll', 'Administracion y Finanzas', array['sueldos', 'liquidacion']),
  ('ejecutivo-cuentas', 'ejecutivo-cuentas', 'Ejecutivo/a de Cuentas', 'Administracion y Finanzas', array[]::text[]),
  ('asistente-virtual', 'asistente-virtual', 'Asistente Virtual', 'Administracion y Finanzas', array[]::text[]),
  ('cadete-administrativo', 'cadete-administrativo', 'Cadete Administrativo', 'Administracion y Finanzas', array[]::text[]),
  ('ingeniero-civil', 'ingeniero-civil', 'Ingeniero/a Civil', 'Ingenieria', array[]::text[]),
  ('ingeniero-industrial', 'ingeniero-industrial', 'Ingeniero/a Industrial', 'Ingenieria', array[]::text[]),
  ('ingeniero-mecanico', 'ingeniero-mecanico', 'Ingeniero/a Mecanico/a', 'Ingenieria', array[]::text[]),
  ('ingeniero-electronico', 'ingeniero-electronico', 'Ingeniero/a Electronico/a', 'Ingenieria', array[]::text[]),
  ('ingeniero-quimico', 'ingeniero-quimico', 'Ingeniero/a Quimico/a', 'Ingenieria', array[]::text[]),
  ('ingeniero-sistemas', 'ingeniero-sistemas', 'Ingeniero/a en Sistemas', 'Ingenieria', array[]::text[]),
  ('arquitecto', 'arquitecto', 'Arquitecto/a', 'Ingenieria y Construccion', array[]::text[]),
  ('agrimensor', 'agrimensor', 'Agrimensor/a', 'Ingenieria y Construccion', array[]::text[]),
  ('abogado', 'abogado', 'Abogado/a General', 'Legales', array[]::text[]),
  ('abogado-laboralista', 'abogado-laboralista', 'Abogado/a Laboralista', 'Legales', array[]::text[]),
  ('abogado-penalista', 'abogado-penalista', 'Abogado/a Penalista', 'Legales', array[]::text[]),
  ('abogado-civil', 'abogado-civil', 'Abogado/a Civil', 'Legales', array[]::text[]),
  ('abogado-corporativo', 'abogado-corporativo', 'Abogado/a Corporativo', 'Legales', array[]::text[]),
  ('escribano', 'escribano', 'Escribano/a', 'Legales', array[]::text[]),
  ('paralegal', 'paralegal', 'Paralegal / Asistente Legal', 'Legales', array[]::text[]),
  ('procurador', 'procurador', 'Procurador/a', 'Legales', array[]::text[]),
  ('disenador-grafico', 'disenador-grafico', 'Disenador/a Grafico/a', 'Diseno y Comunicacion', array[]::text[]),
  ('community-manager', 'community-manager', 'Community Manager', 'Diseno y Comunicacion', array[]::text[]),
  ('redactor-copywriter', 'redactor-copywriter', 'Redactor/a / Copywriter', 'Diseno y Comunicacion', array[]::text[]),
  ('periodista', 'periodista', 'Periodista', 'Diseno y Comunicacion', array[]::text[]),
  ('editor-video', 'editor-video', 'Editor/a de Video', 'Diseno y Comunicacion', array[]::text[]),
  ('fotografo', 'fotografo', 'Fotografo/a', 'Diseno y Comunicacion', array[]::text[]),
  ('productor-audiovisual', 'productor-audiovisual', 'Productor/a Audiovisual', 'Diseno y Comunicacion', array[]::text[]),
  ('especialista-seo', 'especialista-seo', 'Especialista SEO', 'Diseno y Comunicacion', array[]::text[]),
  ('paid-media', 'paid-media', 'Especialista SEM / Paid Media', 'Diseno y Comunicacion', array[]::text[]),
  ('analista-marketing', 'analista-marketing', 'Analista de Marketing', 'Diseno y Comunicacion', array[]::text[]),
  ('social-media-manager', 'social-media-manager', 'Social Media Manager', 'Diseno y Comunicacion', array[]::text[]),
  ('disenador-industrial', 'disenador-industrial', 'Disenador/a Industrial', 'Diseno y Comunicacion', array[]::text[]),
  ('disenador-indumentaria', 'disenador-indumentaria', 'Disenador/a de Indumentaria', 'Diseno y Comunicacion', array[]::text[]),
  ('chofer-camion', 'chofer-camion', 'Chofer de Camion', 'Logistica y Transporte', array[]::text[]),
  ('chofer-colectivo', 'chofer-colectivo', 'Chofer de Colectivo', 'Logistica y Transporte', array[]::text[]),
  ('taxista-remisero', 'taxista-remisero', 'Taxista / Remisero / Uber / Cabify', 'Logistica y Transporte', array[]::text[]),
  ('repartidor', 'repartidor', 'Repartidor/a', 'Logistica y Transporte', array[]::text[]),
  ('chofer-reparto', 'chofer-reparto', 'Chofer de Reparto', 'Logistica y Transporte', array[]::text[]),
  ('operario-deposito', 'operario-deposito', 'Operario/a de Deposito', 'Logistica y Transporte', array[]::text[]),
  ('clarkista', 'clarkista', 'Clarkista / Autoelevadorista', 'Logistica y Transporte', array[]::text[]),
  ('preparador-pedidos', 'preparador-pedidos', 'Preparador/a de Pedidos', 'Logistica y Transporte', array[]::text[]),
  ('supervisor-logistica', 'supervisor-logistica', 'Supervisor/a de Logistica', 'Logistica y Transporte', array[]::text[]),
  ('analista-logistica', 'analista-logistica', 'Analista de Logistica', 'Logistica y Transporte', array[]::text[]),
  ('despachante-aduana', 'despachante-aduana', 'Despachante de Aduana', 'Logistica y Transporte', array[]::text[]),
  ('administrativo-trafico', 'administrativo-trafico', 'Administrativo/a de Trafico', 'Logistica y Transporte', array[]::text[]),
  ('operario-produccion', 'operario-produccion', 'Operario/a de Produccion', 'Industria y Produccion', array[]::text[]),
  ('operario-metalurgico', 'operario-metalurgico', 'Operario/a Metalurgico', 'Industria y Produccion', array[]::text[]),
  ('operario-textil', 'operario-textil', 'Operario/a Textil', 'Industria y Produccion', array[]::text[]),
  ('operario-alimenticio', 'operario-alimenticio', 'Operario/a Alimenticio', 'Industria y Produccion', array[]::text[]),
  ('tecnico-electromecanico', 'tecnico-electromecanico', 'Tecnico/a Electromecanico', 'Industria y Produccion', array[]::text[]),
  ('tecnico-mecanico', 'tecnico-mecanico', 'Tecnico/a Mecanico', 'Industria y Produccion', array[]::text[]),
  ('electricista-industrial', 'electricista-industrial', 'Electricista Industrial', 'Industria y Produccion', array[]::text[]),
  ('supervisor-produccion', 'supervisor-produccion', 'Supervisor/a de Produccion', 'Industria y Produccion', array[]::text[]),
  ('jefe-planta', 'jefe-planta', 'Jefe/a de Planta', 'Industria y Produccion', array[]::text[]),
  ('control-calidad', 'control-calidad', 'Control de Calidad', 'Industria y Produccion', array[]::text[]),
  ('inspector-calidad', 'inspector-calidad', 'Inspector/a de Calidad', 'Industria y Produccion', array[]::text[]),
  ('mantenimiento-industrial', 'mantenimiento-industrial', 'Mantenimiento Industrial', 'Industria y Produccion', array[]::text[]),
  ('tornero', 'tornero', 'Tornero/a', 'Industria y Produccion', array[]::text[]),
  ('matricero', 'matricero', 'Matricero/a', 'Industria y Produccion', array[]::text[]),
  ('peon-rural', 'peon-rural', 'Peon Rural', 'Agro y Rural', array[]::text[]),
  ('tractorista', 'tractorista', 'Tractorista', 'Agro y Rural', array[]::text[]),
  ('ingeniero-agronomo', 'ingeniero-agronomo', 'Ingeniero/a Agronomo', 'Agro y Rural', array[]::text[]),
  ('veterinario', 'veterinario', 'Veterinario/a', 'Agro y Rural', array[]::text[]),
  ('tambero', 'tambero', 'Tambero/a', 'Agro y Rural', array[]::text[]),
  ('encargado-campo', 'encargado-campo', 'Encargado/a de Campo', 'Agro y Rural', array[]::text[]),
  ('operario-avicola', 'operario-avicola', 'Operario/a Avicola', 'Agro y Rural', array[]::text[]),
  ('operario-frigorifico', 'operario-frigorifico', 'Operario/a Frigorifico', 'Agro y Rural', array[]::text[]),
  ('tecnico-agropecuario', 'tecnico-agropecuario', 'Tecnico/a Agropecuario', 'Agro y Rural', array[]::text[]),
  ('policia', 'policia', 'Policia', 'Seguridad', array[]::text[]),
  ('vigilador-privado', 'vigilador-privado', 'Vigilador/a Privado/a', 'Seguridad', array[]::text[]),
  ('bombero', 'bombero', 'Bombero/a', 'Seguridad', array[]::text[]),
  ('militar', 'militar', 'Militar', 'Seguridad', array[]::text[]),
  ('gendarme-prefecto', 'gendarme-prefecto', 'Gendarme / Prefecto', 'Seguridad', array[]::text[]),
  ('operador-monitoreo', 'operador-monitoreo', 'Operador/a de Monitoreo', 'Seguridad', array[]::text[]),
  ('custodio', 'custodio', 'Custodio/a', 'Seguridad', array[]::text[]),
  ('empleada-domestica', 'empleada-domestica', 'Personal de Casas Particulares', 'Servicios Personales', array[]::text[]),
  ('peluquero', 'peluquero', 'Peluquero/a', 'Servicios Personales', array[]::text[]),
  ('barbero', 'barbero', 'Barbero/a', 'Servicios Personales', array[]::text[]),
  ('esteticista', 'esteticista', 'Esteticista', 'Servicios Personales', array[]::text[]),
  ('cosmetologo', 'cosmetologo', 'Cosmetologo/a', 'Servicios Personales', array[]::text[]),
  ('manicura', 'manicura', 'Manicura', 'Servicios Personales', array[]::text[]),
  ('masajista', 'masajista', 'Masajista', 'Servicios Personales', array[]::text[]),
  ('entrenador-personal', 'entrenador-personal', 'Entrenador/a Personal', 'Servicios Personales', array[]::text[]),
  ('profesor-yoga-pilates', 'profesor-yoga-pilates', 'Profesor/a de Yoga / Pilates', 'Servicios Personales', array[]::text[]),
  ('paseador-perros', 'paseador-perros', 'Paseador/a de Perros', 'Servicios Personales', array[]::text[]),
  ('ninera', 'ninera', 'Ninera', 'Servicios Personales', array[]::text[]),
  ('creador-contenido', 'creador-contenido', 'Creador/a de Contenido', 'Otros', array[]::text[]),
  ('streamer', 'streamer', 'Streamer', 'Otros', array[]::text[]),
  ('musico', 'musico', 'Musico/a', 'Otros', array[]::text[]),
  ('artista', 'artista', 'Artista', 'Otros', array[]::text[]),
  ('traductor', 'traductor', 'Traductor/a', 'Otros', array[]::text[]),
  ('guia-turismo', 'guia-turismo', 'Guia de Turismo', 'Otros', array[]::text[])
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  category = excluded.category,
  keywords = excluded.keywords;
