import type { Profession } from './data';

export const FALLBACK_PROFESSIONS: Profession[] = [
  { id: 'programador-web', slug: 'programador-web', name: 'Programador Web', category: 'Tecnologia', keywords: ['desarrollador', 'developer', 'sistemas', 'programacion'] },
  { id: 'desarrollador-backend', slug: 'desarrollador-backend', name: 'Desarrollador Backend', category: 'Tecnologia', keywords: ['programador', 'developer', 'api', 'back'] },
  { id: 'desarrollador-frontend', slug: 'desarrollador-frontend', name: 'Desarrollador Frontend', category: 'Tecnologia', keywords: ['programador', 'developer', 'react', 'front'] },
  { id: 'desarrollador-fullstack', slug: 'desarrollador-fullstack', name: 'Desarrollador Full Stack', category: 'Tecnologia', keywords: ['fullstack', 'programador', 'developer'] },
  { id: 'desarrollador-mobile', slug: 'desarrollador-mobile', name: 'Desarrollador Mobile', category: 'Tecnologia', keywords: ['android', 'ios', 'react native', 'flutter'] },
  { id: 'qa-tester', slug: 'qa-tester', name: 'QA Tester', category: 'Tecnologia', keywords: ['testing', 'calidad', 'tester'] },
  { id: 'qa-automation', slug: 'qa-automation', name: 'QA Automation', category: 'Tecnologia', keywords: ['testing', 'automation', 'selenium', 'cypress'] },
  { id: 'devops-sre', slug: 'devops-sre', name: 'DevOps / SRE', category: 'Tecnologia', keywords: ['infraestructura', 'cloud', 'kubernetes', 'aws'] },
  { id: 'data-scientist', slug: 'data-scientist', name: 'Data Scientist', category: 'Tecnologia', keywords: ['ciencia de datos', 'machine learning', 'ai'] },
  { id: 'data-engineer', slug: 'data-engineer', name: 'Data Engineer', category: 'Tecnologia', keywords: ['ingeniero de datos', 'etl', 'big data'] },
  { id: 'analista-de-datos', slug: 'analista-de-datos', name: 'Analista de Datos', category: 'Tecnologia', keywords: ['data', 'analytics', 'bi'] },
  { id: 'analista-bi', slug: 'analista-bi', name: 'Analista BI', category: 'Tecnologia', keywords: ['business intelligence', 'power bi', 'tableau'] },
  { id: 'product-manager', slug: 'product-manager', name: 'Product Manager', category: 'Tecnologia', keywords: ['pm', 'producto'] },
  { id: 'project-manager-it', slug: 'project-manager-it', name: 'Project Manager IT', category: 'Tecnologia', keywords: ['proyectos', 'it', 'pmo'] },
  { id: 'scrum-master', slug: 'scrum-master', name: 'Scrum Master', category: 'Tecnologia', keywords: ['agile', 'facilitador'] },
  { id: 'disenador-ux-ui', slug: 'disenador-ux-ui', name: 'Disenador UX/UI', category: 'Tecnologia', keywords: ['design', 'web', 'interfaces'] },
  { id: 'product-designer', slug: 'product-designer', name: 'Product Designer', category: 'Tecnologia', keywords: ['ux', 'ui', 'figma'] },
  { id: 'soporte-tecnico', slug: 'soporte-tecnico', name: 'Soporte Tecnico', category: 'Tecnologia', keywords: ['sistemas', 'helpdesk', 'it'] },
  { id: 'help-desk', slug: 'help-desk', name: 'Help Desk', category: 'Tecnologia', keywords: ['mesa de ayuda', 'soporte nivel 1'] },
  { id: 'administrador-redes', slug: 'administrador-redes', name: 'Administrador de Redes', category: 'Tecnologia', keywords: ['networking', 'redes', 'it'] },
  { id: 'sysadmin', slug: 'sysadmin', name: 'Administrador de Sistemas', category: 'Tecnologia', keywords: ['linux', 'windows server', 'infraestructura'] },
  { id: 'ciberseguridad', slug: 'ciberseguridad', name: 'Especialista en Ciberseguridad', category: 'Tecnologia', keywords: ['seguridad informatica', 'security'] },
  { id: 'implementador-erp-crm', slug: 'implementador-erp-crm', name: 'Implementador ERP / CRM', category: 'Tecnologia', keywords: ['sap', 'salesforce', 'odoo', 'hubspot'] },
  { id: 'consultor-sap', slug: 'consultor-sap', name: 'Consultor SAP', category: 'Tecnologia', keywords: ['erp', 'abap', 'fi', 'mm'] },
  { id: 'medico-clinico', slug: 'medico-clinico', name: 'Medico Clinico', category: 'Salud' },
  { id: 'medico-pediatra', slug: 'medico-pediatra', name: 'Medico Pediatra', category: 'Salud' },
  { id: 'medico-cardiologo', slug: 'medico-cardiologo', name: 'Medico Cardiologo', category: 'Salud' },
  { id: 'medico-psiquiatra', slug: 'medico-psiquiatra', name: 'Medico Psiquiatra', category: 'Salud' },
  { id: 'medico-ginecologo', slug: 'medico-ginecologo', name: 'Medico Ginecologo', category: 'Salud' },
  { id: 'medico-traumatologo', slug: 'medico-traumatologo', name: 'Medico Traumatologo', category: 'Salud' },
  { id: 'medico-dermatologo', slug: 'medico-dermatologo', name: 'Medico Dermatologo', category: 'Salud' },
  { id: 'medico-anestesista', slug: 'medico-anestesista', name: 'Medico Anestesista', category: 'Salud' },
  { id: 'enfermero', slug: 'enfermero', name: 'Enfermero/a', category: 'Salud' },
  { id: 'auxiliar-enfermeria', slug: 'auxiliar-enfermeria', name: 'Auxiliar de Enfermeria', category: 'Salud' },
  { id: 'odontologo', slug: 'odontologo', name: 'Odontologo/a', category: 'Salud' },
  { id: 'psicologo', slug: 'psicologo', name: 'Psicologo/a', category: 'Salud' },
  { id: 'kinesiologo', slug: 'kinesiologo', name: 'Kinesiologo/a', category: 'Salud' },
  { id: 'nutricionista', slug: 'nutricionista', name: 'Nutricionista', category: 'Salud' },
  { id: 'farmaceutico', slug: 'farmaceutico', name: 'Farmaceutico/a', category: 'Salud' },
  { id: 'bioquimico', slug: 'bioquimico', name: 'Bioquimico/a', category: 'Salud' },
  { id: 'fonoaudiologo', slug: 'fonoaudiologo', name: 'Fonoaudiologo/a', category: 'Salud' },
  { id: 'acompanante-terapeutico', slug: 'acompanante-terapeutico', name: 'Acompanante Terapeutico', category: 'Salud' },
  { id: 'cuidador-domiciliario', slug: 'cuidador-domiciliario', name: 'Cuidador/a Domiciliario', category: 'Salud' },
  { id: 'tecnico-radiologo', slug: 'tecnico-radiologo', name: 'Tecnico/a Radiologo', category: 'Salud' },
  { id: 'instrumentador-quirurgico', slug: 'instrumentador-quirurgico', name: 'Instrumentador/a Quirurgico', category: 'Salud' },
  { id: 'camillero', slug: 'camillero', name: 'Camillero/a', category: 'Salud' },
  { id: 'administrativo-salud', slug: 'administrativo-salud', name: 'Administrativo/a de Salud', category: 'Salud' },
  { id: 'docente-inicial', slug: 'docente-inicial', name: 'Docente Nivel Inicial', category: 'Educacion' },
  { id: 'docente-primaria', slug: 'docente-primaria', name: 'Docente Nivel Primario', category: 'Educacion' },
  { id: 'docente-secundaria', slug: 'docente-secundaria', name: 'Docente Nivel Secundario', category: 'Educacion' },
  { id: 'docente-universitario', slug: 'docente-universitario', name: 'Docente Universitario', category: 'Educacion' },
  { id: 'profesor-ingles', slug: 'profesor-ingles', name: 'Profesor/a de Ingles', category: 'Educacion' },
  { id: 'profesor-educacion-fisica', slug: 'profesor-educacion-fisica', name: 'Profesor/a de Educacion Fisica', category: 'Educacion' },
  { id: 'preceptor', slug: 'preceptor', name: 'Preceptor/a', category: 'Educacion' },
  { id: 'director-escuela', slug: 'director-escuela', name: 'Director/a de Escuela', category: 'Educacion' },
  { id: 'psicopedagogo', slug: 'psicopedagogo', name: 'Psicopedagogo/a', category: 'Educacion' },
  { id: 'tutor-online', slug: 'tutor-online', name: 'Tutor/a Online', category: 'Educacion' },
  { id: 'profesor-particular', slug: 'profesor-particular', name: 'Profesor/a Particular', category: 'Educacion' },
  { id: 'plomero', slug: 'plomero', name: 'Plomero', category: 'Oficios y Construccion' },
  { id: 'electricista', slug: 'electricista', name: 'Electricista', category: 'Oficios y Construccion' },
  { id: 'gasista', slug: 'gasista', name: 'Gasista Matriculado', category: 'Oficios y Construccion' },
  { id: 'albanil', slug: 'albanil', name: 'Albanil', category: 'Oficios y Construccion' },
  { id: 'carpintero', slug: 'carpintero', name: 'Carpintero/a', category: 'Oficios y Construccion' },
  { id: 'herrero', slug: 'herrero', name: 'Herrero/a', category: 'Oficios y Construccion' },
  { id: 'pintor', slug: 'pintor', name: 'Pintor/a', category: 'Oficios y Construccion' },
  { id: 'mecanico-automotor', slug: 'mecanico-automotor', name: 'Mecanico/a Automotor', category: 'Oficios y Construccion' },
  { id: 'cerrajero', slug: 'cerrajero', name: 'Cerrajero/a', category: 'Oficios y Construccion' },
  { id: 'tecnico-aire-acondicionado', slug: 'tecnico-aire-acondicionado', name: 'Tecnico/a Aire Acondicionado', category: 'Oficios y Construccion' },
  { id: 'tecnico-refrigeracion', slug: 'tecnico-refrigeracion', name: 'Tecnico/a Refrigeracion', category: 'Oficios y Construccion' },
  { id: 'jardinero', slug: 'jardinero', name: 'Jardinero/a', category: 'Oficios y Construccion' },
  { id: 'piletero', slug: 'piletero', name: 'Piletero/a', category: 'Oficios y Construccion' },
  { id: 'fumigador', slug: 'fumigador', name: 'Fumigador/a', category: 'Oficios y Construccion' },
  { id: 'techista', slug: 'techista', name: 'Techista', category: 'Oficios y Construccion' },
  { id: 'durlockero', slug: 'durlockero', name: 'Durlockero/a', category: 'Oficios y Construccion' },
  { id: 'soldador', slug: 'soldador', name: 'Soldador/a', category: 'Oficios y Construccion' },
  { id: 'maestro-mayor-obras', slug: 'maestro-mayor-obras', name: 'Maestro Mayor de Obras', category: 'Oficios y Construccion' },
  { id: 'vendedor-local', slug: 'vendedor-local', name: 'Vendedor/a de Local', category: 'Comercio y Ventas' },
  { id: 'cajero', slug: 'cajero', name: 'Cajero/a', category: 'Comercio y Ventas' },
  { id: 'repositor', slug: 'repositor', name: 'Repositor/a', category: 'Comercio y Ventas' },
  { id: 'encargado-local', slug: 'encargado-local', name: 'Encargado/a de Local', category: 'Comercio y Ventas' },
  { id: 'supervisor-local', slug: 'supervisor-local', name: 'Supervisor/a de Local', category: 'Comercio y Ventas' },
  { id: 'preventista', slug: 'preventista', name: 'Preventista', category: 'Comercio y Ventas' },
  { id: 'vendedor-telefonico', slug: 'vendedor-telefonico', name: 'Vendedor/a Telefonico', category: 'Comercio y Ventas' },
  { id: 'telemarketer', slug: 'telemarketer', name: 'Telemarketer', category: 'Comercio y Ventas' },
  { id: 'atencion-cliente', slug: 'atencion-cliente', name: 'Atencion al Cliente', category: 'Comercio y Ventas' },
  { id: 'customer-support', slug: 'customer-support', name: 'Customer Support', category: 'Comercio y Ventas' },
  { id: 'customer-success', slug: 'customer-success', name: 'Customer Success', category: 'Comercio y Ventas' },
  { id: 'promotor', slug: 'promotor', name: 'Promotor/a', category: 'Comercio y Ventas' },
  { id: 'merchandiser', slug: 'merchandiser', name: 'Merchandiser', category: 'Comercio y Ventas' },
  { id: 'corredor-inmobiliario', slug: 'corredor-inmobiliario', name: 'Corredor/a Inmobiliario/a', category: 'Comercio y Ventas' },
  { id: 'cocinero', slug: 'cocinero', name: 'Cocinero/a', category: 'Gastronomia' },
  { id: 'chef', slug: 'chef', name: 'Chef', category: 'Gastronomia' },
  { id: 'mozo-camarero', slug: 'mozo-camarero', name: 'Mozo/a / Camarero/a', category: 'Gastronomia', keywords: ['camarero', 'mozo', 'waiter'] },
  { id: 'barista', slug: 'barista', name: 'Barista', category: 'Gastronomia' },
  { id: 'bartender', slug: 'bartender', name: 'Bartender', category: 'Gastronomia' },
  { id: 'ayudante-cocina', slug: 'ayudante-cocina', name: 'Ayudante de Cocina', category: 'Gastronomia' },
  { id: 'bachero', slug: 'bachero', name: 'Bachero/a', category: 'Gastronomia' },
  { id: 'pastelero', slug: 'pastelero', name: 'Pastelero/a', category: 'Gastronomia' },
  { id: 'panadero', slug: 'panadero', name: 'Panadero/a', category: 'Gastronomia' },
  { id: 'parrillero', slug: 'parrillero', name: 'Parrillero/a', category: 'Gastronomia' },
  { id: 'pizzero', slug: 'pizzero', name: 'Pizzero/a', category: 'Gastronomia' },
  { id: 'jefe-cocina', slug: 'jefe-cocina', name: 'Jefe/a de Cocina', category: 'Gastronomia' },
  { id: 'encargado-restaurante', slug: 'encargado-restaurante', name: 'Encargado/a de Restaurante', category: 'Gastronomia' },
  { id: 'recepcionista-hotel', slug: 'recepcionista-hotel', name: 'Recepcionista de Hotel', category: 'Gastronomia' },
  { id: 'mucama-hotel', slug: 'mucama-hotel', name: 'Mucama/o de Hotel', category: 'Gastronomia' },
  { id: 'contador-publico', slug: 'contador-publico', name: 'Contador/a Publico/a', category: 'Administracion y Finanzas' },
  { id: 'administrativo', slug: 'administrativo', name: 'Administrativo/a', category: 'Administracion y Finanzas' },
  { id: 'asistente-administrativo', slug: 'asistente-administrativo', name: 'Asistente Administrativo', category: 'Administracion y Finanzas' },
  { id: 'data-entry', slug: 'data-entry', name: 'Data Entry / Carga de Datos', category: 'Administracion y Finanzas', keywords: ['data enter', 'data entry', 'carga de datos', 'administrativo'] },
  { id: 'recepcionista', slug: 'recepcionista', name: 'Recepcionista', category: 'Administracion y Finanzas' },
  { id: 'secretario', slug: 'secretario', name: 'Secretario/a', category: 'Administracion y Finanzas' },
  { id: 'analista-contable', slug: 'analista-contable', name: 'Analista Contable', category: 'Administracion y Finanzas' },
  { id: 'analista-financiero', slug: 'analista-financiero', name: 'Analista Financiero', category: 'Administracion y Finanzas' },
  { id: 'liquidador-sueldos', slug: 'liquidador-sueldos', name: 'Liquidador/a de Sueldos', category: 'Administracion y Finanzas' },
  { id: 'auditor', slug: 'auditor', name: 'Auditor/a', category: 'Administracion y Finanzas' },
  { id: 'tesorero', slug: 'tesorero', name: 'Tesorero/a', category: 'Administracion y Finanzas' },
  { id: 'analista-facturacion', slug: 'analista-facturacion', name: 'Analista de Facturacion', category: 'Administracion y Finanzas' },
  { id: 'analista-compras', slug: 'analista-compras', name: 'Analista de Compras', category: 'Administracion y Finanzas' },
  { id: 'analista-rrhh', slug: 'analista-rrhh', name: 'Analista de RRHH', category: 'Administracion y Finanzas', keywords: ['recursos humanos'] },
  { id: 'recruiter', slug: 'recruiter', name: 'Recruiter / Selector/a de Personal', category: 'Administracion y Finanzas', keywords: ['seleccion', 'rrhh'] },
  { id: 'payroll', slug: 'payroll', name: 'Payroll', category: 'Administracion y Finanzas', keywords: ['sueldos', 'liquidacion'] },
  { id: 'ejecutivo-cuentas', slug: 'ejecutivo-cuentas', name: 'Ejecutivo/a de Cuentas', category: 'Administracion y Finanzas' },
  { id: 'asistente-virtual', slug: 'asistente-virtual', name: 'Asistente Virtual', category: 'Administracion y Finanzas' },
  { id: 'cadete-administrativo', slug: 'cadete-administrativo', name: 'Cadete Administrativo', category: 'Administracion y Finanzas' },
  { id: 'ingeniero-civil', slug: 'ingeniero-civil', name: 'Ingeniero/a Civil', category: 'Ingenieria' },
  { id: 'ingeniero-industrial', slug: 'ingeniero-industrial', name: 'Ingeniero/a Industrial', category: 'Ingenieria' },
  { id: 'ingeniero-mecanico', slug: 'ingeniero-mecanico', name: 'Ingeniero/a Mecanico/a', category: 'Ingenieria' },
  { id: 'ingeniero-electronico', slug: 'ingeniero-electronico', name: 'Ingeniero/a Electronico/a', category: 'Ingenieria' },
  { id: 'ingeniero-quimico', slug: 'ingeniero-quimico', name: 'Ingeniero/a Quimico/a', category: 'Ingenieria' },
  { id: 'ingeniero-sistemas', slug: 'ingeniero-sistemas', name: 'Ingeniero/a en Sistemas', category: 'Ingenieria' },
  { id: 'arquitecto', slug: 'arquitecto', name: 'Arquitecto/a', category: 'Ingenieria y Construccion' },
  { id: 'agrimensor', slug: 'agrimensor', name: 'Agrimensor/a', category: 'Ingenieria y Construccion' },
  { id: 'abogado', slug: 'abogado', name: 'Abogado/a General', category: 'Legales' },
  { id: 'abogado-laboralista', slug: 'abogado-laboralista', name: 'Abogado/a Laboralista', category: 'Legales' },
  { id: 'abogado-penalista', slug: 'abogado-penalista', name: 'Abogado/a Penalista', category: 'Legales' },
  { id: 'abogado-civil', slug: 'abogado-civil', name: 'Abogado/a Civil', category: 'Legales' },
  { id: 'abogado-corporativo', slug: 'abogado-corporativo', name: 'Abogado/a Corporativo', category: 'Legales' },
  { id: 'escribano', slug: 'escribano', name: 'Escribano/a', category: 'Legales' },
  { id: 'paralegal', slug: 'paralegal', name: 'Paralegal / Asistente Legal', category: 'Legales' },
  { id: 'procurador', slug: 'procurador', name: 'Procurador/a', category: 'Legales' },
  { id: 'disenador-grafico', slug: 'disenador-grafico', name: 'Disenador/a Grafico/a', category: 'Diseno y Comunicacion' },
  { id: 'community-manager', slug: 'community-manager', name: 'Community Manager', category: 'Diseno y Comunicacion' },
  { id: 'redactor-copywriter', slug: 'redactor-copywriter', name: 'Redactor/a / Copywriter', category: 'Diseno y Comunicacion' },
  { id: 'periodista', slug: 'periodista', name: 'Periodista', category: 'Diseno y Comunicacion' },
  { id: 'editor-video', slug: 'editor-video', name: 'Editor/a de Video', category: 'Diseno y Comunicacion' },
  { id: 'fotografo', slug: 'fotografo', name: 'Fotografo/a', category: 'Diseno y Comunicacion' },
  { id: 'productor-audiovisual', slug: 'productor-audiovisual', name: 'Productor/a Audiovisual', category: 'Diseno y Comunicacion' },
  { id: 'especialista-seo', slug: 'especialista-seo', name: 'Especialista SEO', category: 'Diseno y Comunicacion' },
  { id: 'paid-media', slug: 'paid-media', name: 'Especialista SEM / Paid Media', category: 'Diseno y Comunicacion' },
  { id: 'analista-marketing', slug: 'analista-marketing', name: 'Analista de Marketing', category: 'Diseno y Comunicacion' },
  { id: 'social-media-manager', slug: 'social-media-manager', name: 'Social Media Manager', category: 'Diseno y Comunicacion' },
  { id: 'disenador-industrial', slug: 'disenador-industrial', name: 'Disenador/a Industrial', category: 'Diseno y Comunicacion' },
  { id: 'disenador-indumentaria', slug: 'disenador-indumentaria', name: 'Disenador/a de Indumentaria', category: 'Diseno y Comunicacion' },
  { id: 'chofer-camion', slug: 'chofer-camion', name: 'Chofer de Camion', category: 'Logistica y Transporte' },
  { id: 'chofer-colectivo', slug: 'chofer-colectivo', name: 'Chofer de Colectivo', category: 'Logistica y Transporte' },
  { id: 'taxista-remisero', slug: 'taxista-remisero', name: 'Taxista / Remisero / Uber / Cabify', category: 'Logistica y Transporte' },
  { id: 'repartidor', slug: 'repartidor', name: 'Repartidor/a', category: 'Logistica y Transporte' },
  { id: 'chofer-reparto', slug: 'chofer-reparto', name: 'Chofer de Reparto', category: 'Logistica y Transporte' },
  { id: 'operario-deposito', slug: 'operario-deposito', name: 'Operario/a de Deposito', category: 'Logistica y Transporte' },
  { id: 'clarkista', slug: 'clarkista', name: 'Clarkista / Autoelevadorista', category: 'Logistica y Transporte' },
  { id: 'preparador-pedidos', slug: 'preparador-pedidos', name: 'Preparador/a de Pedidos', category: 'Logistica y Transporte' },
  { id: 'supervisor-logistica', slug: 'supervisor-logistica', name: 'Supervisor/a de Logistica', category: 'Logistica y Transporte' },
  { id: 'analista-logistica', slug: 'analista-logistica', name: 'Analista de Logistica', category: 'Logistica y Transporte' },
  { id: 'despachante-aduana', slug: 'despachante-aduana', name: 'Despachante de Aduana', category: 'Logistica y Transporte' },
  { id: 'administrativo-trafico', slug: 'administrativo-trafico', name: 'Administrativo/a de Trafico', category: 'Logistica y Transporte' },
  { id: 'operario-produccion', slug: 'operario-produccion', name: 'Operario/a de Produccion', category: 'Industria y Produccion' },
  { id: 'operario-metalurgico', slug: 'operario-metalurgico', name: 'Operario/a Metalurgico', category: 'Industria y Produccion' },
  { id: 'operario-textil', slug: 'operario-textil', name: 'Operario/a Textil', category: 'Industria y Produccion' },
  { id: 'operario-alimenticio', slug: 'operario-alimenticio', name: 'Operario/a Alimenticio', category: 'Industria y Produccion' },
  { id: 'tecnico-electromecanico', slug: 'tecnico-electromecanico', name: 'Tecnico/a Electromecanico', category: 'Industria y Produccion' },
  { id: 'tecnico-mecanico', slug: 'tecnico-mecanico', name: 'Tecnico/a Mecanico', category: 'Industria y Produccion' },
  { id: 'electricista-industrial', slug: 'electricista-industrial', name: 'Electricista Industrial', category: 'Industria y Produccion' },
  { id: 'supervisor-produccion', slug: 'supervisor-produccion', name: 'Supervisor/a de Produccion', category: 'Industria y Produccion' },
  { id: 'jefe-planta', slug: 'jefe-planta', name: 'Jefe/a de Planta', category: 'Industria y Produccion' },
  { id: 'control-calidad', slug: 'control-calidad', name: 'Control de Calidad', category: 'Industria y Produccion' },
  { id: 'inspector-calidad', slug: 'inspector-calidad', name: 'Inspector/a de Calidad', category: 'Industria y Produccion' },
  { id: 'mantenimiento-industrial', slug: 'mantenimiento-industrial', name: 'Mantenimiento Industrial', category: 'Industria y Produccion' },
  { id: 'tornero', slug: 'tornero', name: 'Tornero/a', category: 'Industria y Produccion' },
  { id: 'matricero', slug: 'matricero', name: 'Matricero/a', category: 'Industria y Produccion' },
  { id: 'peon-rural', slug: 'peon-rural', name: 'Peon Rural', category: 'Agro y Rural' },
  { id: 'tractorista', slug: 'tractorista', name: 'Tractorista', category: 'Agro y Rural' },
  { id: 'ingeniero-agronomo', slug: 'ingeniero-agronomo', name: 'Ingeniero/a Agronomo', category: 'Agro y Rural' },
  { id: 'veterinario', slug: 'veterinario', name: 'Veterinario/a', category: 'Agro y Rural' },
  { id: 'tambero', slug: 'tambero', name: 'Tambero/a', category: 'Agro y Rural' },
  { id: 'encargado-campo', slug: 'encargado-campo', name: 'Encargado/a de Campo', category: 'Agro y Rural' },
  { id: 'operario-avicola', slug: 'operario-avicola', name: 'Operario/a Avicola', category: 'Agro y Rural' },
  { id: 'operario-frigorifico', slug: 'operario-frigorifico', name: 'Operario/a Frigorifico', category: 'Agro y Rural' },
  { id: 'tecnico-agropecuario', slug: 'tecnico-agropecuario', name: 'Tecnico/a Agropecuario', category: 'Agro y Rural' },
  { id: 'policia', slug: 'policia', name: 'Policia', category: 'Seguridad' },
  { id: 'vigilador-privado', slug: 'vigilador-privado', name: 'Vigilador/a Privado/a', category: 'Seguridad' },
  { id: 'bombero', slug: 'bombero', name: 'Bombero/a', category: 'Seguridad' },
  { id: 'militar', slug: 'militar', name: 'Militar', category: 'Seguridad' },
  { id: 'gendarme-prefecto', slug: 'gendarme-prefecto', name: 'Gendarme / Prefecto', category: 'Seguridad' },
  { id: 'operador-monitoreo', slug: 'operador-monitoreo', name: 'Operador/a de Monitoreo', category: 'Seguridad' },
  { id: 'custodio', slug: 'custodio', name: 'Custodio/a', category: 'Seguridad' },
  { id: 'empleada-domestica', slug: 'empleada-domestica', name: 'Personal de Casas Particulares', category: 'Servicios Personales' },
  { id: 'peluquero', slug: 'peluquero', name: 'Peluquero/a', category: 'Servicios Personales' },
  { id: 'barbero', slug: 'barbero', name: 'Barbero/a', category: 'Servicios Personales' },
  { id: 'esteticista', slug: 'esteticista', name: 'Esteticista', category: 'Servicios Personales' },
  { id: 'cosmetologo', slug: 'cosmetologo', name: 'Cosmetologo/a', category: 'Servicios Personales' },
  { id: 'manicura', slug: 'manicura', name: 'Manicura', category: 'Servicios Personales' },
  { id: 'masajista', slug: 'masajista', name: 'Masajista', category: 'Servicios Personales' },
  { id: 'entrenador-personal', slug: 'entrenador-personal', name: 'Entrenador/a Personal', category: 'Servicios Personales' },
  { id: 'profesor-yoga-pilates', slug: 'profesor-yoga-pilates', name: 'Profesor/a de Yoga / Pilates', category: 'Servicios Personales' },
  { id: 'paseador-perros', slug: 'paseador-perros', name: 'Paseador/a de Perros', category: 'Servicios Personales' },
  { id: 'ninera', slug: 'ninera', name: 'Ninera', category: 'Servicios Personales' },
  { id: 'creador-contenido', slug: 'creador-contenido', name: 'Creador/a de Contenido', category: 'Otros' },
  { id: 'streamer', slug: 'streamer', name: 'Streamer', category: 'Otros' },
  { id: 'musico', slug: 'musico', name: 'Musico/a', category: 'Otros' },
  { id: 'artista', slug: 'artista', name: 'Artista', category: 'Otros' },
  { id: 'traductor', slug: 'traductor', name: 'Traductor/a', category: 'Otros' },
  { id: 'guia-turismo', slug: 'guia-turismo', name: 'Guia de Turismo', category: 'Otros' },
];
